// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAutostartEnabled():Promise<boolean>;

export function GetGlobalAuth():Promise<main.GlobalAuth>;

export function GetLocalIP():Promise<string>;

export function GetPersistedShares():Promise<Array<main.ShareMount>>;

export function SaveSharesState(arg1:Array<main.ShareMount>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetAutostartEnabled(arg1:boolean):Promise<void>;

export function SetGlobalAuth(arg1:string,arg2:string):Promise<void>;

export function StartWebDAV(arg1:string,arg2:number):Promise<void>;

export function StopWebDAV(arg1:number):Promise<void>;
