// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAutostartEnabled() {
  return window['go']['main']['App']['GetAutostartEnabled']();
}

export function GetGlobalAuth() {
  return window['go']['main']['App']['GetGlobalAuth']();
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetPersistedShares() {
  return window['go']['main']['App']['GetPersistedShares']();
}

export function SaveSharesState(arg1) {
  return window['go']['main']['App']['SaveSharesState'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetAutostartEnabled(arg1) {
  return window['go']['main']['App']['SetAutostartEnabled'](arg1);
}

export function SetGlobalAuth(arg1, arg2) {
  return window['go']['main']['App']['SetGlobalAuth'](arg1, arg2);
}

export function StartWebDAV(arg1, arg2) {
  return window['go']['main']['App']['StartWebDAV'](arg1, arg2);
}

export function StopWebDAV(arg1) {
  return window['go']['main']['App']['StopWebDAV'](arg1);
}
